"""Check upstream.lock.json against the upstream copies and derived tables under sources/.

upstream.lock.json records, for every file under sources/ that is a copy of or is generated from a third-party upstream, its size and SHA-256 and the upstream it comes from, plus the repository and commit of each upstream. This record, not msime, is the authority for those bytes: msime's resources/dictionary-sources.lock.json pins no file of this repository. The msime builder (crates/dict-builder, `msime-dict-build --dictionary`) enforces the record when it reads this repository: it verifies the bytes it reads against the entries here, requires every file it treats as upstream data to be listed under the upstream name it gives that file, and requires each recorded upstream commit to equal the reference of that name in msime's lock (`mozc` against its Mozc revision). Moving an upstream to a new commit therefore needs the msime change (the reference and the licence texts) first; an edit here plus `--update` that also changes a recorded commit passes this script but fails the build until msime matches. This script only gives pull requests early feedback: it checks the record's structure, that every recorded file still has the recorded bytes, that every upstream file under sources/ is recorded, and that no generated table header names a dirty msime worktree. It does not compare commits against msime or fetch anything from the upstreams.

Usage:
    python3 scripts/check_upstream.py
    python3 scripts/check_upstream.py --update PATH...   # rewrite size and sha256 of recorded PATHs from their current bytes
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
RECORD = ROOT / "upstream.lock.json"

# Mirror of `UPSTREAM_FILES` in msime crates/dict-builder/src/sources.rs. The msime builder is authoritative; this copy only drives the early checks here, and any change to the builder's list must be followed here. The first matching entry wins, and an entry ending in `/` matches every path under that directory, so the exact HKCanCor path listed before `sources/cantonese/` names its own upstream.
UPSTREAM_FILES = (
    ("sources/pinyin/rime-ice.txt", "rime-ice"),
    ("sources/pinyin/rime-ice-supplement.txt", "rime-ice-supplement"),
    ("sources/english/rime-ice-en-supplement.txt", "rime-ice-supplement"),
    ("sources/cantonese/hkcancor-word-counts.txt", "hkcancor"),
    ("sources/cantonese/", "rime-cantonese"),
    ("sources/english/scowl-words.txt", "SCOWL"),
    ("sources/zhuyin/tsi.csv", "libchewing-data"),
    ("sources/zhuyin/word.csv", "libchewing-data"),
    ("sources/zhuyin/mcbopomofo-supplement.txt", "McBopomofo"),
    ("sources/zhuyin/phrase.occ", "McBopomofo"),
    ("sources/stroke/", "rime-stroke"),
    ("sources/japanese/", "mozc"),
    ("sources/korean/", "libhangul"),
    ("sources/wubi/wubi98.txt", "98wubi-tables"),
    ("sources/wubi/wubi98-fcitx.txt", "fcitx5-table-extra"),
)

# Tables generated by msime-dict-build. The generator writes the msime commit it ran from into line 1 and appends `-dirty` when that worktree had uncommitted changes; such a header does not identify the generator and must not be merged.
GENERATED = (
    "sources/pinyin/places.txt",
    "sources/english/scowl-words.txt",
    "sources/wubi/wubi86-supplement.txt",
    "sources/cantonese/hkcancor-word-counts.txt",
)

COMMIT = re.compile(r"^[0-9a-f]{40}$")
SHA256 = re.compile(r"^[0-9a-f]{64}$")
DIRTY_HEADER = re.compile(r"msime 仓库提交 [0-9a-f]{40}-dirty")


def upstream_reference(path: str) -> str | None:
    for upstream, reference in UPSTREAM_FILES:
        if upstream.endswith("/"):
            if path.startswith(upstream):
                return reference
        elif path == upstream:
            return reference
    return None


def measure(path: Path) -> tuple[int, str]:
    data = path.read_bytes()
    return len(data), hashlib.sha256(data).hexdigest()


def tracked_sources() -> list[str]:
    output = subprocess.run(
        ["git", "ls-files", "-z", "sources"],
        cwd=ROOT,
        check=True,
        capture_output=True,
    ).stdout
    return [path for path in output.decode("utf-8").split("\0") if path]


def load_record() -> dict:
    with RECORD.open(encoding="utf-8") as handle:
        return json.load(handle)


def write_record(record: dict) -> None:
    record["files"].sort(key=lambda entry: entry["path"])
    RECORD.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")


def check(record: dict) -> list[str]:
    failures: list[str] = []

    if record.get("version") != 1:
        failures.append(f"{RECORD.name}: version must be 1, got {record.get('version')!r}")

    upstreams = record.get("upstreams")
    if not isinstance(upstreams, dict) or not upstreams:
        failures.append(f"{RECORD.name}: upstreams must be a non-empty object")
        upstreams = {}
    for name, upstream in upstreams.items():
        if not isinstance(upstream, dict):
            failures.append(f"upstream {name}: must be an object with repository and commit")
            continue
        repository = upstream.get("repository")
        if not isinstance(repository, str) or not repository.startswith("https://github.com/"):
            failures.append(f"upstream {name}: repository must start with https://github.com/, got {repository!r}")
        commit = upstream.get("commit")
        if not isinstance(commit, str) or not COMMIT.match(commit):
            failures.append(f"upstream {name}: commit must be 40 lowercase hex digits, got {commit!r}")

    files = record.get("files")
    if not isinstance(files, list):
        failures.append(f"{RECORD.name}: files must be an array")
        files = []

    tracked = tracked_sources()
    tracked_set = set(tracked)
    recorded: set[str] = set()
    used: set[str] = set()
    for entry in files:
        if not isinstance(entry, dict) or not isinstance(entry.get("path"), str):
            failures.append(f"{RECORD.name}: file entry without a path: {entry!r}")
            continue
        path = entry["path"]
        if path in recorded:
            failures.append(f"{path}: recorded more than once")
            continue
        recorded.add(path)

        upstream = entry.get("upstream")
        expected_upstream = upstream_reference(path)
        if upstream not in upstreams:
            failures.append(f"{path}: upstream {upstream!r} is not in upstreams")
        else:
            used.add(upstream)
        if expected_upstream is None:
            failures.append(f"{path}: not an upstream file in UPSTREAM_FILES, so it must not be recorded")
        elif upstream != expected_upstream:
            failures.append(f"{path}: upstream must be {expected_upstream!r} (UPSTREAM_FILES), got {upstream!r}")

        size = entry.get("size")
        sha256 = entry.get("sha256")
        if not isinstance(size, int) or isinstance(size, bool) or size < 0:
            failures.append(f"{path}: size must be a non-negative integer, got {size!r}")
            continue
        if not isinstance(sha256, str) or not SHA256.match(sha256):
            failures.append(f"{path}: sha256 must be 64 lowercase hex digits, got {sha256!r}")
            continue
        if path not in tracked_set:
            failures.append(f"{path}: not a file tracked under sources/")
            continue
        actual_size, actual_sha256 = measure(ROOT / path)
        if (actual_size, actual_sha256) != (size, sha256):
            failures.append(f"{path}: expected {size}/{sha256} got {actual_size}/{actual_sha256}")

    for path in tracked:
        reference = upstream_reference(path)
        if reference is not None and path not in recorded:
            failures.append(f"{path}: coverage: upstream file of {reference} is not recorded in {RECORD.name}")

    for name in upstreams:
        if name not in used:
            failures.append(f"upstream {name}: no recorded file uses it")

    for path in GENERATED:
        if path not in tracked_set:
            failures.append(f"{path}: generated table is not a file tracked under sources/; when msime renames or drops it, update GENERATED here too")
            continue
        with (ROOT / path).open("rb") as handle:
            header = handle.readline().decode("utf-8", errors="replace")
        if DIRTY_HEADER.search(header):
            failures.append(f"{path}: line 1 names a dirty msime worktree; regenerate it from a clean msime checkout")

    return failures


def update(record: dict, paths: list[str]) -> list[str]:
    entries = {entry["path"]: entry for entry in record["files"]}
    failures: list[str] = []
    for path in paths:
        entry = entries.get(path)
        if entry is None:
            failures.append(f"{path}: not recorded in {RECORD.name}; --update only refreshes existing entries")
            continue
        entry["size"], entry["sha256"] = measure(ROOT / path)
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--update",
        nargs="+",
        metavar="PATH",
        help="rewrite size and sha256 of these recorded paths from their current bytes, then check",
    )
    arguments = parser.parse_args()

    record = load_record()
    if arguments.update:
        failures = update(record, arguments.update)
        if failures:
            for failure in failures:
                print(f"FAIL: {failure}")
            return 1
        write_record(record)
        print(f"updated {len(arguments.update)} entries in {RECORD.name}")

    failures = check(record)
    if failures:
        for failure in failures:
            print(f"FAIL: {failure}")
        return 1
    print(f"OK: {len(record['files'])} files from {len(record['upstreams'])} upstreams match {RECORD.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
